// packages/react/src/components/CheersForm.tsx
import React, { RefAttributes, useContext, useImperativeHandle, useMemo, useRef } from 'react';
import { BaseField, FormType } from 'cheers-form-core';
import mitt from 'mitt';
import { CheersFormContext, CheersFormContextValue, FormEvents } from './CheersFormContext';
import { useCheersFieldState } from '../hooks/useCheersFieldState';

interface CheersFormProps<T extends Record<string, any>> {
  form: FormType<T>;
  children?: React.ReactNode;
  style?: React.CSSProperties;
  className?: string;
  onScrollIntoView?: (el: HTMLElement) => void;
}

interface FormInstanceRef<T extends Record<string, any>> {
  el: HTMLDivElement | null;
  instance: FormType<T>;
  scrollTo: (field: BaseField<unknown>) => void;
}

export const CheersForm = React.forwardRef(
  <T extends Record<string, any>>(
    { form, children, style, className, onScrollIntoView }: CheersFormProps<T>,
    ref: React.Ref<FormInstanceRef<T>>,
  ) => {
    const parentContext = useContext(CheersFormContext);
    const formRef = useRef<HTMLDivElement>(null);
    const providerValue = useMemo(() => {
      return {
        form,
        emitter: parentContext ? parentContext.emitter : mitt<FormEvents>(),
        scrollIntoView: onScrollIntoView ?? ((el: HTMLElement) => el.scrollIntoView({ behavior: 'smooth' })),
      } as CheersFormContextValue<FormEvents>;
    }, [form, parentContext]);
    useImperativeHandle(
      ref,
      () => {
        return {
          el: formRef.current,
          instance: form,
          scrollTo(field: BaseField<unknown>) {
            providerValue.emitter.emit('scroll', field);
          },
        };
      },
      [form, formRef.current],
    );
    useCheersFieldState(form as BaseField<unknown>);
    return (
      <CheersFormContext.Provider value={providerValue}>
        <div className={className} ref={formRef} style={style}>
          {children}
        </div>
      </CheersFormContext.Provider>
    );
  },
  // 实现React.forwardRef泛型类型
) as <T extends Record<string, any>>(props: CheersFormProps<T> & RefAttributes<FormInstanceRef<T>>) => JSX.Element;

// packages/vue3/src/components/CheersForm.vue
<template>
  <div ref="el">
    <slot></slot>
  </div>
</template>
<script lang="ts" setup generic="T extends Record<string, any>">
import { BaseField, FormType } from 'cheers-form-core';
import { getCurrentInstance, onUpdated, provide } from 'vue';
import mitt from 'mitt';
import { useCheersFieldState } from '../hooks/useCheersFieldState';
import { CheersFormContext } from './CheersFormContext';
import { FormEvents } from './FormEvents';

const props = defineProps<{
  form: FormType<T>;
  onScrollIntoView?: (el: HTMLElement) => void;
}>();
const instance = getCurrentInstance();
const emitter = mitt<FormEvents>();

provide<CheersFormContext<T>>('form', {
  el: instance?.refs['el'] as HTMLElement,
  emitter: emitter,
  instance: props.form,
  scrollIntoView: (el: HTMLElement)=> props?.onScrollIntoView?.(el)
});

defineExpose({
  scrollTo: (field: BaseField<unknown>)=> emitter.emit('scroll', field)
})

useCheersFieldState(props.form as BaseField<unknown>);
</script>
